services:
  api:
    container_name: bookworm-api
    build:
      dockerfile: docker/Dockerfile.api
      args:
        ENVIRONMENT_AREA: DEVELOPMENT
    ports:
      - 8000:8000
    env_file:
      - ./env/.env.dev
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/

  db:
    container_name: pg-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai:
    container_name: bookworm-ai
    image: alpine/ollama
    ports:
      - 5000:5000
    env_file:
      - ./env/.env.dev
    depends_on:
      - db
    volumes:
      - model_data:/root/.ollama/models
  redis:
    container_name: bookworm-redis
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - redis_db:/data
volumes:
  postgres_data:
  model_data:
  redis_db:
