name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        version: v24.0.9
          

    - name: Cleanup the environment
      run: make destroy

    - name: Build the application
      run: make setup

    - name: Run unit and integration test
      run: make test
